#!/bin/bash

# This script is for use with Linux/macOS/Unix.
# It was auto-generated by near-runner-ava,
# and only runs the tests in the `near-runner` folder.
cd near-runner
npm install
npm run test -- $@ # pass along any CLI flags, such as `--verbose`