name: Tests
on: push
jobs:
  testnet:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: yarn && yarn test:testnet:ci
  sandbox:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [14, 15, 16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: yarn && yarn test:sandbox:ci
  near-sandbox-install:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: yarn && rm node_modules/binary-install/bin/near-sandbox && yarn test:sandbox
